from datetime import date

from tools.check_report_freshness import inspect_report


def write_report(path, generated_on: str) -> None:
    path.write_text(
        "# report\n\n"
        f"> Generated by [vigil-risk](https://pypi.org/project/vigil-risk/) on {generated_on}.\n",
        encoding="utf-8",
    )


def test_report_within_max_age_is_fresh(tmp_path):
    report = tmp_path / "report.md"
    write_report(report, "2026-05-01")

    result = inspect_report(report, today=date(2026, 5, 12), max_age_days=30)

    assert result.status == "fresh"
    assert result.age_days == 11


def test_report_beyond_max_age_is_stale(tmp_path):
    report = tmp_path / "report.md"
    write_report(report, "2026-03-27")

    result = inspect_report(report, today=date(2026, 5, 12), max_age_days=30)

    assert result.status == "stale"
    assert result.age_days == 46


def test_report_without_generated_date_fails_closed(tmp_path):
    report = tmp_path / "report.md"
    report.write_text("# report\n", encoding="utf-8")

    result = inspect_report(report, today=date(2026, 5, 12), max_age_days=30)

    assert result.status == "missing-date"
    assert result.generated_on is None
