#!/usr/bin/env python3
"""Check whether generated dependency-risk reports are fresh enough."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path


DEFAULT_MAX_AGE_DAYS = 30
GENERATED_RE = re.compile(
    r"Generated by \[vigil-risk\]\(https://pypi\.org/project/vigil-risk/\) on "
    r"(?P<date>\d{4}-\d{2}-\d{2})"
)


@dataclass(frozen=True)
class ReportFreshness:
    path: Path
    generated_on: date | None
    age_days: int | None
    status: str


def report_paths(root: Path) -> list[Path]:
    paths = [root / "ai-agent-dependency-risk.md"]
    paths.extend(sorted((root / "reports").glob("*.md")))
    return paths


def inspect_report(path: Path, *, today: date, max_age_days: int) -> ReportFreshness:
    text = path.read_text(encoding="utf-8")
    match = GENERATED_RE.search(text)
    if not match:
        return ReportFreshness(path=path, generated_on=None, age_days=None, status="missing-date")

    generated_on = date.fromisoformat(match.group("date"))
    age_days = (today - generated_on).days
    if age_days < 0:
        status = "future-date"
    elif age_days > max_age_days:
        status = "stale"
    else:
        status = "fresh"
    return ReportFreshness(
        path=path,
        generated_on=generated_on,
        age_days=age_days,
        status=status,
    )


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fail if generated vigil-risk reports are too old for current security decisions."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Repository root to scan. Defaults to the current directory.",
    )
    parser.add_argument(
        "--max-age-days",
        type=int,
        default=DEFAULT_MAX_AGE_DAYS,
        help=f"Maximum acceptable report age. Defaults to {DEFAULT_MAX_AGE_DAYS} days.",
    )
    parser.add_argument(
        "--today",
        type=date.fromisoformat,
        default=date.today(),
        help="Override today's date as YYYY-MM-DD for reproducible checks.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    root = args.root.resolve()
    paths = report_paths(root)

    missing_files = [path for path in paths if not path.exists()]
    if missing_files:
        for path in missing_files:
            print(f"MISSING {path.relative_to(root)}")
        return 2

    results = [
        inspect_report(path, today=args.today, max_age_days=args.max_age_days)
        for path in paths
    ]
    failing = [item for item in results if item.status != "fresh"]

    print(
        f"Checked {len(results)} reports; max age {args.max_age_days} days; "
        f"as of {args.today.isoformat()}."
    )
    if failing:
        for item in failing:
            rel = item.path.relative_to(root)
            if item.generated_on is None:
                print(f"FAIL {rel}: missing generated date")
            else:
                print(
                    f"FAIL {rel}: {item.status}, generated {item.generated_on.isoformat()} "
                    f"({item.age_days} days old)"
                )
        return 1

    oldest = max(results, key=lambda item: item.age_days or 0)
    print(
        f"OK oldest={oldest.path.relative_to(root)} "
        f"generated={oldest.generated_on.isoformat()} age_days={oldest.age_days}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
